### ISSUE TITLE
Installing of bash completion on Debian Buster failed when docker_version is set 

### ISSUE THREAD

**Issue by frzb** [igor-nikiforov/ansible-role-docker#7]
Given this minimal Ansible play running against Debian Buster

```
- hosts: test
  become: yes
  roles:
    - igor_nikiforov.docker
  vars:
    docker_version: 5:20.10.11~3-0~debian-buster
```

The Ansible run fails for the task installing the bash completion

```
TASK [igor_nikiforov.docker : Install Docker bash completion.] *****************
fatal: [test]: FAILED! => {"changed": false, "dest": "/etc/bash_completion.d/docker", "elapsed": 0, "msg": "Request failed", "response": "HTTP Error 404: Not Found", "status_code": 404, "url": "https://raw.githubusercontent.com/docker/cli/v5:20.10.11~3-0~debian-buster/contrib/completion/bash/docker"}
```
Looks like version strings on Debian and on the Github Docker CLI repository are no longer compatible.
